config/routes.rb
Rails.application.routes.draw do
  resources :propiedads
  resources :conjuntos
  resources :contactos
  root "visitantes#index"
  
  resources :residentes do 
    resources :detallespersonas, module: :residentes
   end 

  resources :visitantes do 
    resources :detallespersonas, module: :visitantes
   end 


end

app/models/detallespersona.rb
class Detallespersona < ApplicationRecord
  belongs_to :personable, polymorphic: true
end

app/controllers/detallespersonas_controller.rb
class DetallespersonasController < ApplicationController
  #before_action :set_detallespersona, only: [:show, :edit, :update, :destroy]

  # GET /detallespersonas
  # GET /detallespersonas.json
  #def index
  #  @detallespersonas = Detallespersona.all
  #end

  # GET /detallespersonas/1
  # GET /detallespersonas/1.json
  #def show
  #end

  # GET /detallespersonas/new
  def new
    @detallespersona = @personable.detallespersonas.new
  end

  # GET /detallespersonas/1/edit
  #def edit
  #end

  # POST /detallespersonas
  # POST /detallespersonas.json
  def create

    @detallespersona = @personable.detallespersonas.new(detallespersona_params)   
    @personable.save
    redirect_to @personable, notice: 'Detallespersona was successfully created.'


    #@detallespersona = Detallespersona.new(detallespersona_params)
    #respond_to do |format|
    #  if @detallespersona.save
    #    format.html { redirect_to @detallespersona, notice: 'Detallespersona was successfully created.' }
    #    format.json { render :show, status: :created, location: @detallespersona }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @detallespersona.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PATCH/PUT /detallespersonas/1
  # PATCH/PUT /detallespersonas/1.json
  #def update
  #  respond_to do |format|
  #    if @detallespersona.update(detallespersona_params)
  #      format.html { redirect_to @detallespersona, notice: 'Detallespersona was successfully updated.' }
  #      format.json { render :show, status: :ok, location: @detallespersona }
  #    else
  #      format.html { render :edit }
  #      format.json { render json: @detallespersona.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end
#
  ## DELETE /detallespersonas/1
  ## DELETE /detallespersonas/1.json
  #def destroy
  #  @detallespersona.destroy
  #  respond_to do |format|
  #    format.html { redirect_to detallespersonas_url, notice: 'Detallespersona was successfully destroyed.' }
  #    format.json { head :no_content }
  #  end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_detallespersona
    #  @detallespersona = Detallespersona.find(params[:id])
    #end

    # Only allow a list of trusted parameters through.
    def detallespersona_params
      params.require(:detallespersona).permit(:personable_id, :personable_type, :apellido, :edad, :cedula, :huella_digital)
    end
end

app/controllers/residentes/detallespersonas_controller.rb
class Residentes::DetallespersonasController < DetallespersonasController

  before_action :set_personable

  private

    def set_personable
      @personable = Residente.find(params[:residente_id])
    end

end

app/controllers/visitantes/detallespersonas_controller.rb
class Visitantes::DetallespersonasController < DetallespersonasController

  before_action :set_personable

  private

    def set_personable
      @personable = Visitante.find(params[:visitante_id])
    end

end

app/helpers/detallespersonas_helper.rb
module DetallespersonasHelper
end

app/views/detallespersonas/_detallespersonas.html.erb
<h3> Detalles Personales </h3>
<% personable.detallespersonas.each do |detallespersona| %>
  <%= detallespersona.nombre %><br>

<% end %>

app/views/detallespersonas/_form.html.erb
<!-- <%#= form_with(model: [personable, Detallespersona.new], local: true) do |form| %>


  <div class="field">
    <%#= form.label :nombre %>
    <%#= form.text_field :nombre %>
  </div>



  <div class="actions">
    <%#= form.submit %>
  </div>
<%# end %> -->

<%#= form.fields_for :detallespersonas, personable.detallespersonas.last.present? ? personable.detallespersonas.last : 
	Detallespersona.new do |f| %>

  <%#= f.label :nombre %>
  <%#= f.text_field :nombre %>
<%# end %>

app/views/detallespersonas/edit.html.erb
<h1>Editing Detallespersona</h1>

<%= render 'form', detallespersona: @detallespersona %>

<%= link_to 'Show', @detallespersona %> |
<%= link_to 'Back', detallespersonas_path %>

app/views/detallespersonas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Detallespersonas</h1>

<table>
  <thead>
    <tr>
      <th>Personable</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Edad</th>
      <th>Cedula</th>
      <th>Huella digital</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @detallespersonas.each do |detallespersona| %>
      <tr>
        <td><%= detallespersona.personable_id %></td>
        <td><%= detallespersona.nombre %></td>
        <td><%= detallespersona.apellido %></td>
        <td><%= detallespersona.edad %></td>
        <td><%= detallespersona.cedula %></td>
        <td><%= detallespersona.huella_digital %></td>
        <td><%= link_to 'Show', detallespersona %></td>
        <td><%= link_to 'Edit', edit_detallespersona_path(detallespersona) %></td>
        <td><%= link_to 'Destroy', detallespersona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detallespersona', new_detallespersona_path %>

app/views/detallespersonas/new.html.erb
<h1>New Detallespersona</h1>

<%= render 'form', detallespersona: @detallespersona %>

<%= link_to 'Back', detallespersonas_path %>

app/views/detallespersonas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Personable:</strong>
  <%= @detallespersona.personable_id %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @detallespersona.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @detallespersona.apellido %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @detallespersona.edad %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @detallespersona.cedula %>
</p>

<p>
  <strong>Huella digital:</strong>
  <%= @detallespersona.huella_digital %>
</p>

<%= link_to 'Edit', edit_detallespersona_path(@detallespersona) %> |
<%= link_to 'Back', detallespersonas_path %>