config/routes.rb
Rails.application.routes.draw do
  resources :propiedads
  resources :conjuntos
  resources :contactos
  root "visitantes#index"
  
  resources :residentes do 
    resources :detallespersonas, module: :residentes
   end 

  resources :visitantes do 
    resources :detallespersonas, module: :visitantes
   end 


end

app/models/conjunto.rb
class Conjunto < ApplicationRecord
  has_many :propiedades
  has_many :residentes, through: :propiedades 
end

app/controllers/conjuntos_controller.rb
class ConjuntosController < ApplicationController
  before_action :set_conjunto, only: [:show, :edit, :update, :destroy]

  # GET /conjuntos
  # GET /conjuntos.json
  def index
    @conjuntos = Conjunto.all
  end

  # GET /conjuntos/1
  # GET /conjuntos/1.json
  def show
  end

  # GET /conjuntos/new
  def new
    @conjunto = Conjunto.new
  end

  # GET /conjuntos/1/edit
  def edit
  end

  # POST /conjuntos
  # POST /conjuntos.json
  def create
    @conjunto = Conjunto.new(conjunto_params)

    respond_to do |format|
      if @conjunto.save
        format.html { redirect_to @conjunto, notice: 'Conjunto was successfully created.' }
        format.json { render :show, status: :created, location: @conjunto }
      else
        format.html { render :new }
        format.json { render json: @conjunto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conjuntos/1
  # PATCH/PUT /conjuntos/1.json
  def update
    respond_to do |format|
      if @conjunto.update(conjunto_params)
        format.html { redirect_to @conjunto, notice: 'Conjunto was successfully updated.' }
        format.json { render :show, status: :ok, location: @conjunto }
      else
        format.html { render :edit }
        format.json { render json: @conjunto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conjuntos/1
  # DELETE /conjuntos/1.json
  def destroy
    @conjunto.destroy
    respond_to do |format|
      format.html { redirect_to conjuntos_url, notice: 'Conjunto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conjunto
      @conjunto = Conjunto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def conjunto_params
      params.require(:conjunto).permit(:nombre)
    end
end

app/helpers/conjuntos_helper.rb
module ConjuntosHelper
end

app/views/conjuntos/_form.html.erb
<%= form_with(model: conjunto, local: true) do |form| %>
  <% if conjunto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conjunto.errors.count, "error") %> prohibited this conjunto from being saved:</h2>

      <ul>
        <% conjunto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conjuntos/edit.html.erb
<h1>Editing Conjunto</h1>

<%= render 'form', conjunto: @conjunto %>

<%= link_to 'Show', @conjunto %> |
<%= link_to 'Back', conjuntos_path %>

app/views/conjuntos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conjuntos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conjuntos.each do |conjunto| %>
      <tr>
        <td><%= conjunto.nombre %></td>
        <td><%= link_to 'Show', conjunto %></td>
        <td><%= link_to 'Edit', edit_conjunto_path(conjunto) %></td>
        <td><%= link_to 'Destroy', conjunto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conjunto', new_conjunto_path %>

app/views/conjuntos/new.html.erb
<h1>New Conjunto</h1>

<%= render 'form', conjunto: @conjunto %>

<%= link_to 'Back', conjuntos_path %>

app/views/conjuntos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @conjunto.nombre %>
</p>

<%= link_to 'Edit', edit_conjunto_path(@conjunto) %> |
<%= link_to 'Back', conjuntos_path %>