config/routes.rb
Rails.application.routes.draw do
  resources :propiedads
  resources :conjuntos
  resources :contactos
  root "visitantes#index"
  
  resources :residentes do 
    resources :detallespersonas, module: :residentes
   end 

  resources :visitantes do 
    resources :detallespersonas, module: :visitantes
   end 


end

app/models/visitante.rb
class Visitante < ApplicationRecord
  has_many :detallespersonas, as: :personable
  has_one :contacto, as: :contactable
  accepts_nested_attributes_for :detallespersonas, allow_destroy: true
  accepts_nested_attributes_for :contacto, allow_destroy: true
end

app/controllers/visitantes/detallespersonas_controller.rb
class Visitantes::DetallespersonasController < DetallespersonasController

  before_action :set_personable

  private

    def set_personable
      @personable = Visitante.find(params[:visitante_id])
    end

end

app/controllers/visitantes_controller.rb
class VisitantesController < ApplicationController
  before_action :set_visitante, only: [:show, :edit, :update, :destroy]

  # GET /visitantes
  # GET /visitantes.json
  def index
    @visitantes = Visitante.all
  end

  # GET /visitantes/1
  # GET /visitantes/1.json
  def show
  end

  # GET /visitantes/new
  def new
    @visitante = Visitante.new
  end

  # GET /visitantes/1/edit
  def edit
  end

  # POST /visitantes
  # POST /visitantes.json
  def create
    @visitante = Visitante.new(visitante_params)

    respond_to do |format|
      if @visitante.save
        format.html { redirect_to @visitante, notice: 'Visitante was successfully created.' }
        format.json { render :show, status: :created, location: @visitante }
      else
        format.html { render :new }
        format.json { render json: @visitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitantes/1
  # PATCH/PUT /visitantes/1.json
  def update
    respond_to do |format|
      if @visitante.update(visitante_params)
        format.html { redirect_to @visitante, notice: 'Visitante was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitante }
      else
        format.html { render :edit }
        format.json { render json: @visitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitantes/1
  # DELETE /visitantes/1.json
  def destroy
    @visitante.destroy
    respond_to do |format|
      format.html { redirect_to visitantes_url, notice: 'Visitante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitante
      @visitante = Visitante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitante_params
      params.require(:visitante).permit( detallespersonas_attributes: [:id, :nombre, :apellido, :edad, :cedula, :huella_digital],
       contacto_attributes: [:id, :telefono, :email, :celular])
    end
end

app/helpers/visitantes_helper.rb
module VisitantesHelper
end

app/views/visitantes/_contacto.html.erb
<%= form.fields_for :contacto, @visitante.contacto.present? ? 
	@visitante.contacto : Contacto.new do |f| %>

	<div class="detallesForm">
	  <%= f.label :telefono %>
	  <%= f.text_field :telefono %>
	</div>
	<div class="detallesForm">
	  <%= f.label :celular %>
	  <%= f.text_field :celular%>
	</div>
	<div class="detallesForm">
	  <%= f.label :email %>
	  <%= f.text_field :email %>
	</div>

<% end %>

app/views/visitantes/_detallespersona.html.erb
<%= form.fields_for :detallespersonas, @visitante.detallespersonas.last.present? ? @visitante.detallespersonas.last : @visitante.detallespersonas.new do |f| %>

	<div class="detallesForm">
	  <%= f.label :nombre %>
	  <%= f.text_field :nombre %>
	</div>
	<div class="detallesForm">
	  <%= f.label :apellido %>
	  <%= f.text_field :apellido %>
	</div>
	<div class="detallesForm">
	  <%= f.label :edad%>
	  <%= f.text_field :edad %>
	</div>
	<div class="detallesForm">
	  <%= f.label :cedula %>
	  <%= f.text_field :cedula %>
	</div>
	<div class="detallesForm">
	  <%= f.label :huella_digital %>
	  <%= f.text_field :huella_digital %>
	</div>

<% end %>

app/views/visitantes/_form.html.erb
<div class="card-body"> 
  <%= form_with(model: visitante, local: true) do |form| %>
  <% if visitante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitante.errors.count, "error") %> prohibited this visitante from being saved:</h2>

      <ul>
        <% visitante.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
    <%= render 'visitantes/detallespersona', form: form %>
<br>
    <%#= render partial: "detallespersonas/form", locals: {personable: @visitante}, form: form  %>
     <br>
    <%= render 'visitantes/contacto', form: form %>

    <div class="actions">
      <%= form.submit %>
    </div>
  
  <% end %>
</div>



<%#= render partial: "detallespersonas/form", form: form, locals: {personable: @visitante} %>
 

      <%#= render partial: "detallespersonas/form", locals: {personable: @visitante} Unable to make it work %> 

      <%#=  NO GOOD  form.fields_for :detallespersonas do |f| %>
       <%#= form.fields_for :detallespersonas, detallespersonas[0].present? ? detallespersonas[0] : Detallespersonas.new do |f|  NO GOOD %>

      <%#= form.fields_for :locations, @user.locations[0].present? ? @user.locations[0] : Location.new  do |f| NO GOOD%>



     <%#= form.fields_for :detallespersonas, @visitante.detallespersonas.last.present? ? @visitante.detallespersonas.last : @visitante.detallespersonas.new do |f| %>

        <%#= f.label :nombre %>
        <%#= f.text_field :nombre %>
      <%# end %>

app/views/visitantes/edit.html.erb
<h1>Editing Visitante</h1>

<%= render 'form', visitante: @visitante %>

<%= link_to 'Show', @visitante %> |
<%= link_to 'Back', visitantes_path %>

app/views/visitantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visitantes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Edad</th>
      <th>Cedula</th>
      <th>Huella Digital</th>
      <th>Telefono</th>
      <th>Celular</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @visitantes.each do |visitante| %>
      <tr>
        <td><%= visitante.detallespersonas.last.nombre  %></td>
        <td><%= visitante.detallespersonas.last.apellido  %></td>
        <td><%= visitante.detallespersonas.last.edad  %></td>
        <td><%= visitante.detallespersonas.last.cedula  %></td>
        <td><%= visitante.detallespersonas.last.huella_digital  %></td>
        <td><%= visitante.contacto.telefono %></td>
        <td><%= visitante.contacto.celular %></td>
        <td><%= visitante.contacto.email %></td>
        <td><%= link_to 'Show', visitante %></td>
        <td><%= link_to 'Edit', edit_visitante_path(visitante) %></td>
        <td><%= link_to 'Destroy', visitante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visitante', new_visitante_path %>

app/views/visitantes/new.html.erb
<h1>New Visitante</h1>

<%= render 'form', visitante: @visitante %>

<%= link_to 'Back', visitantes_path %>

app/views/visitantes/show.html.erb
<p id="notice"><%= notice %></p>

<h3> Detalles Personales </h3>

<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Nombre:</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @visitante.detallespersonas.last.nombre %>
  </div>
</div>

<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Apellido :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @visitante.detallespersonas.last.apellido %>
  </div>
</div>

<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Edad :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @visitante.detallespersonas.last.edad %>
  </div>
</div>

<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Cedula :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @visitante.detallespersonas.last.cedula%>
  </div>
</div>

<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Huela Digital :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @visitante.detallespersonas.last.huella_digital %>
  </div>
</div>
<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Telefono :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @visitante.contacto.telefono %>
  </div>
</div>
<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Celular :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @visitante.contacto.celular %>
  </div>
</div>
<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> E-mail :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @visitante.contacto.email %>
  </div>
</div>





<%#= render partial: "detallespersonas/detallespersonas", locals: {personable: @visitante} %>

<%#= render partial: "detallespersonas/form", locals: {personable: @visitante} %>
<br>
<%= link_to 'Edit', edit_visitante_path(@visitante) %> |
<%= link_to 'Back', visitantes_path %>