config/routes.rb
Rails.application.routes.draw do
  resources :propiedads
  resources :conjuntos
  resources :contactos
  root "visitantes#index"
  
  resources :residentes do 
    resources :detallespersonas, module: :residentes
   end 

  resources :visitantes do 
    resources :detallespersonas, module: :visitantes
   end 


end

app/models/residente.rb
class Residente < ApplicationRecord
  has_many :detallespersonas, as: :personable
  has_one :contacto, as: :contactable
  has_many :propiedades
  has_many :conjuntos, through: :propiedades 
  accepts_nested_attributes_for :detallespersonas, allow_destroy: true
  accepts_nested_attributes_for :contacto, allow_destroy: true
end

app/controllers/residentes/contacto.rb
class Residentes::ContactosController < ContactosController

  before_action :set_contactable

  private

    def set_personable
      @contactable = Residente.find(params[:residente_id])
    end

end

app/controllers/residentes/detallespersonas_controller.rb
class Residentes::DetallespersonasController < DetallespersonasController

  before_action :set_personable

  private

    def set_personable
      @personable = Residente.find(params[:residente_id])
    end

end

app/controllers/residentes_controller.rb
class ResidentesController < ApplicationController
  before_action :set_residente, only: [:show, :edit, :update, :destroy]

  # GET /residentes
  # GET /residentes.json
  def index
    @residentes = Residente.all
  end

  # GET /residentes/1
  # GET /residentes/1.json
  def show
  end

  # GET /residentes/new
  def new
    @residente = Residente.new
  end

  # GET /residentes/1/edit
  def edit
  end

  # POST /residentes
  # POST /residentes.json
  def create
    @residente = Residente.new(residente_params)

    respond_to do |format|
      if @residente.save
        format.html { redirect_to @residente, notice: 'Residente was successfully created.' }
        format.json { render :show, status: :created, location: @residente }
      else
        format.html { render :new }
        format.json { render json: @residente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residentes/1
  # PATCH/PUT /residentes/1.json
  def update
    respond_to do |format|
      if @residente.update(residente_params)
        format.html { redirect_to @residente, notice: 'Residente was successfully updated.' }
        format.json { render :show, status: :ok, location: @residente }
      else
        format.html { render :edit }
        format.json { render json: @residente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residentes/1
  # DELETE /residentes/1.json
  def destroy
    @residente.destroy
    respond_to do |format|
      format.html { redirect_to residentes_url, notice: 'Residente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residente
      @residente = Residente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def residente_params
      params.require(:residente).permit(:principal, 
        detallespersonas_attributes: [:id, :nombre, :apellido, :edad, :cedula, :huella_digital], 
        contacto_attributes: [:id, :telefono, :email, :celular])
    end
end

app/helpers/residentes_helper.rb
module ResidentesHelper
end

app/views/residentes/_contacto.html.erb
<%= form.fields_for :contacto, @residente.contacto.present? ? @residente.contacto : Contacto.new do |f| %>

	<div class="detallesForm">
	  <%= f.label :telefono %>
	  <%= f.text_field :telefono %>
	</div>
	<div class="detallesForm">
	  <%= f.label :celular %>
	  <%= f.text_field :celular%>
	</div>
	<div class="detallesForm">
	  <%= f.label :email %>
	  <%= f.text_field :email %>
	</div>
	

<% end %>

app/views/residentes/_detallespersona.html.erb
<%= form.fields_for :detallespersonas, @residente.detallespersonas.last.present? ? @residente.detallespersonas.last : Detallespersona.new do |f| %>

	<div class="detallesForm">
	  <%= f.label :nombre %>
	  <%= f.text_field :nombre %>
	</div>
	<div class="detallesForm">
	  <%= f.label :apellido %>
	  <%= f.text_field :apellido %>
	</div>
	<div class="detallesForm">
	  <%= f.label :edad%>
	  <%= f.text_field :edad %>
	</div>
	<div class="detallesForm">
	  <%= f.label :cedula %>
	  <%= f.text_field :cedula %>
	</div>
	<div class="detallesForm">
	  <%= f.label :huella_digital %>
	  <%= f.text_field :huella_digital %>
	</div>

<% end %>

app/views/residentes/_form.html.erb
<%= form_with(model: residente, local: true) do |form| %>
  <% if residente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(residente.errors.count, "error") %> prohibited this residente from being saved:</h2>

      <ul>
        <% residente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card-body"> 
    <div class="field">
      <%= form.label :principal %>
      <%= form.check_box :principal %>
    </div>
    <%#= render 'residentes/detallespersona', form: form %>
    <%= render 'residentes/detallespersona', form: form %>
    <br>
    <%= render 'residentes/contacto', form: form %>
  </div>

<br>
<br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/residentes/edit.html.erb
<h1>Editing Residente</h1>

<%= render 'form', residente: @residente %>

<%= link_to 'Show', @residente %> |
<%= link_to 'Back', residentes_path %>

app/views/residentes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Residentes</h1>

<table>
  <thead>
    <tr>
      <th>Principal</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Edad</th>
      <th>Cedula</th>
      <th>Huella Digital</th>
      <th>Telefono</th>
      <th>Celular</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @residentes.each do |residente| %>
      <tr>
        <td><%= residente.principal %></td>
        <td><%= residente.detallespersonas.last.nombre %></td>
        <td><%= residente.detallespersonas.last.apellido %></td>
        <td><%= residente.detallespersonas.last.edad %></td>
        <td><%= residente.detallespersonas.last.cedula %></td>
        <td><%= residente.detallespersonas.last.huella_digital %></td>
        <td><%= residente.contacto.telefono %></td>
        <td><%= residente.contacto.celular %></td>
        <td><%= residente.contacto.email %></td>
        <td><%= link_to 'Show', residente %></td>
        <td><%= link_to 'Edit', edit_residente_path(residente) %></td>
        <td><%= link_to 'Destroy', residente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Residente', new_residente_path %>

app/views/residentes/new.html.erb
<h1>New Residente</h1>

<%= render 'form', residente: @residente %>

<%= link_to 'Back', residentes_path %>

app/views/residentes/show.html.erb
<p id="notice"><%= notice %></p>

<h3> Detalles Personales </h3>
<p>
  <strong>Principal:</strong>
  <%= @residente.principal %>
</p>

<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Nombre:</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @residente.detallespersonas.last.nombre %>
  </div>
</div>

<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Apellido :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @residente.detallespersonas.last.apellido %>
  </div>
</div>

<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Edad :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @residente.detallespersonas.last.edad %>
  </div>
</div>

<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Cedula :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @residente.detallespersonas.last.cedula%>
  </div>
</div>

<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Huela Digital :</b>
</div>
<div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @residente.detallespersonas.last.huella_digital %>
  </div>
</div>

<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Telefono :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @residente.contacto.telefono %>
  </div>
</div>
<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> Celular :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @residente.contacto.celular %>
  </div>
</div>
<div class="row">
  <div class="d-inline col-sm-6 company-Showlabels ">
     <b> E-mail :</b>
  </div>
  <div class="d-inline col-sm-6 mb-3 company-Showinputs">
   <%= @residente.contacto.email %>
  </div>
</div>

<%#= render partial: "detallespersonas/detallespersonas", locals: {personable: @residente} %>
<%#= render partial: "detallespersonas/form", locals: {personable: @residente} %>

<%= link_to 'Edit', edit_residente_path(@residente) %> |
<%= link_to 'Back', residentes_path %>


<br>